### ISSUE TITLE
Why Python 3.7 is needed?

### ISSUE THREAD

**Issue by davidtavarez** [byt3bl33d3r/SILENTTRINITY#2]
Wondering why exactly Python 3.7 is needed. Any thoughts? Thanks.

**Comment by byt3bl33d3r** [comment]
this could run on Python 3.6 as well but nothing less than that. 
Main reason for Python 3.7 is because of the command decorator [here](https://github.com/byt3bl33d3r/SILENTTRINITY/blob/master/Server/core/utils.py#L16-L42) which if i recall correctly used some functionality introduced in Python 3.7.
