### ISSUE TITLE
Deal with them backslashes

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/SILENTTRINITY#88]
Backslashes are currently not handled by the CLI so specifying windows paths is a PITA to say the least, needs to be dealt with to preserve my sanity.

![image](https://user-images.githubusercontent.com/5151193/64321595-15cb8880-cf7e-11e9-9f67-55d93165f30c.png)

**Comment by daddycocoaman** [comment]
Try specifying paths with backticks instead of quotation marks. That way users only have to worry about quoting paths when there's a space. So for minidump, try:

> file = `` `DUMPFILE_PATH` ``

If the path requires quotes cause of spaces, the user can do that themselves.

**Comment by jeffmcjunkin** [comment]
Why not single quotes? The same issue affects meterpreter, fwiw

**Comment by daddycocoaman** [comment]
> Why not single quotes? The same issue affects meterpreter, fwiw

It's because Boolang is still gonna remove the slashes, since single quotes and double quotes are treated the same. 
![image](https://user-images.githubusercontent.com/21189155/64591613-1473d480-d35f-11e9-9065-45789264bf35.png)

I set the dumpfile option to `C:\Windows\Temp\debug.bin` while using single/double quotes in the minidump.boo module can got that error (red circle). Using Boolang backticks for paths corrected the error while uncomplicating things with quotes, since it doesn't matter if the user sets the parameter with single or double quotes. This also takes care of spaces in the filename since backticks in Boolang make the string literal:

![image](https://user-images.githubusercontent.com/21189155/64591980-d925d580-d35f-11e9-870d-70d20caf4e83.png)

**Comment by byt3bl33d3r** [comment]
Closing since @daddycocoaman took care of this with backticks, I think that's the way to go.
Cheers
